{% set name = "astrolink" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astrolink-{{ version }}.tar.gz
  sha256: f79f43c06e5658133814288cf44e7af820668c37d2870315ccc523821946ad19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - numpy
    - numba
    - pykdtree
    - scipy
    - scikit-learn
    - matplotlib

test:
  imports:
    - astrolink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/william-h-oliver/astrolink
  summary: A general-purpose algorithm for finding astrophysically-relevant clusters from point-cloud data.
  license: MIT
  license_family: MIT
  license_file:
    - COPYING.md
    - LICENSE.md
  doc_url: https://astrolink.readthedocs.io/
  dev_url: https://github.com/william-h-oliver/astrolink

extra:
  recipe-maintainers:
    - william-h-oliver
